version: '3.4'

services:
  apicalculojuros:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - api=http://localhost:80
    ports:
      - "80"
    networks:
      - my-network     
  
networks:
  my-network:
    external: true